<?php
function alsp_upgrade_notice2(){ ?>
	<div class="notice alsp-notice notice-error">
		<p><?php echo esc_html__('Listing', 'ALSP'); ?> <?php echo ALSP_VERSION ?> <?php echo esc_html__(' Required Database Upgrade, please click below to update database.', 'ALSP'); ?></p>
		<div class="">
			<form method="post" enctype="multipart/form-data">
				<button id="alsp_db_update2" class="update_submit" type="submit" name="alsp_db_update2"><?php echo esc_html__('Update', 'ALSP'); ?></button>
			</form>
		</div>
	</div>
<?php
}
//add_action('admin_notices', 'alsp_upgrade_notice2');
add_action( 'pt-ocdi/before_content_import', 'pacz_import_content_fields' );
/* if(isset($_POST['alsp_db_update2'])){ 
			pacz_import_content_fields();
			//header("Refresh:0");
		} */
function pacz_import_content_fields(){
global $wpdb;
$wpdb->query("INSERT INTO {$wpdb->alsp_content_fields} (`is_core_field`, `order_num`, `name`, `slug`, `description`, `fieldwidth`, `fieldwidth_archive`, `type`, `icon_image`, `is_required`, `is_configuration_page`, `is_search_configuration_page`, `is_ordered`, `is_hide_name`, `is_hide_name_on_grid`, `is_hide_name_on_list`, `is_hide_name_on_search`, `is_field_in_line`, `on_exerpt_page`, `on_exerpt_page_list`, `on_listing_page`, `on_search_form`, `on_map`, `advanced_search_form`, `categories`, `options`, `checkbox_icon_type`, `search_options`, `group_id`) VALUES(1, 16, 'Summary', 'summary', '', '', '', 'excerpt', '', 0, 0, 0, 0, 0, 'hide', 'hide', 1, 0, 0, 1, 0, 0, 0, 0, '', '', '', '', 0);");
$wpdb->query("INSERT INTO {$wpdb->alsp_content_fields} (`is_core_field`, `order_num`, `name`, `slug`, `description`, `fieldwidth`, `fieldwidth_archive`, `type`, `icon_image`, `is_required`, `is_configuration_page`, `is_search_configuration_page`, `is_ordered`, `is_hide_name`, `is_hide_name_on_grid`, `is_hide_name_on_list`, `is_hide_name_on_search`, `is_field_in_line`, `on_exerpt_page`, `on_exerpt_page_list`, `on_listing_page`, `on_search_form`, `on_map`, `advanced_search_form`, `categories`, `options`, `checkbox_icon_type`, `search_options`, `group_id`) VALUES(1, 18, 'Address', 'address', '', '', '', 'address', 'alsp-fa-map-marker', 0, 0, 0, 0, 0, 'hide',  'hide', 1, 0, 0, 1, 0, 0, 0, 0, '', '', '', '', 1);");
$wpdb->query("INSERT INTO {$wpdb->alsp_content_fields} (`is_core_field`, `order_num`, `name`, `slug`, `description`, `fieldwidth`, `fieldwidth_archive`, `type`, `icon_image`, `is_required`, `is_configuration_page`, `is_search_configuration_page`, `is_ordered`, `is_hide_name`, `is_hide_name_on_grid`, `is_hide_name_on_list`, `is_hide_name_on_search`, `is_field_in_line`, `on_exerpt_page`, `on_exerpt_page_list`, `on_listing_page`, `on_search_form`, `on_map`, `advanced_search_form`, `categories`, `options`, `checkbox_icon_type`, `search_options`, `group_id`) VALUES(1, 22, 'Description', 'content', '', NULL, '', 'content', '', 0, 0, 0, 0, 0, 'hide',  'hide', 1, 0, 0, 1, 0, 0, 0, 0, '', '', '', '', 0);");
$wpdb->query("INSERT INTO {$wpdb->alsp_content_fields} (`is_core_field`, `order_num`, `name`, `slug`, `description`, `fieldwidth`, `fieldwidth_archive`, `type`, `icon_image`, `is_required`, `is_configuration_page`, `is_search_configuration_page`, `is_ordered`, `is_hide_name`, `is_hide_name_on_grid`, `is_hide_name_on_list`, `is_hide_name_on_search`, `is_field_in_line`, `on_exerpt_page`, `on_exerpt_page_list`, `on_listing_page`, `on_search_form`, `on_map`, `advanced_search_form`, `categories`, `options`, `checkbox_icon_type`, `search_options`, `group_id`) VALUES(1, 17, 'Brand and Model', 'categories_list', '', '', '', 'categories', '', 0, 0, 0, 0, 0, 'hide', 'hide', 1, 0, 0, 0, 1, 0, 0, 0, '', '', '', '', 1);");
$wpdb->query("INSERT INTO {$wpdb->alsp_content_fields} (`is_core_field`, `order_num`, `name`, `slug`, `description`, `fieldwidth`, `fieldwidth_archive`, `type`, `icon_image`, `is_required`, `is_configuration_page`, `is_search_configuration_page`, `is_ordered`, `is_hide_name`, `is_hide_name_on_grid`, `is_hide_name_on_list`, `is_hide_name_on_search`, `is_field_in_line`, `on_exerpt_page`, `on_exerpt_page_list`, `on_listing_page`, `on_search_form`, `on_map`, `advanced_search_form`, `categories`, `options`, `checkbox_icon_type`, `search_options`, `group_id`) VALUES(1, 19, 'Listing Tags', 'listing_tags', '', '', '', 'tags', '', 0, 0, 0, 0, 0, 'hide', 'hide', 1, 0, 0, 0, 1, 0, 0, 0, '', '', '', '', 1);");
$wpdb->query("INSERT INTO {$wpdb->alsp_content_fields} (`is_core_field`, `order_num`, `name`, `slug`, `description`, `fieldwidth`, `fieldwidth_archive`, `type`, `icon_image`, `is_required`, `is_configuration_page`, `is_search_configuration_page`, `is_ordered`, `is_hide_name`, `is_hide_name_on_grid`, `is_hide_name_on_list`, `is_hide_name_on_search`, `is_field_in_line`, `on_exerpt_page`, `on_exerpt_page_list`, `on_listing_page`, `on_search_form`, `on_map`, `advanced_search_form`, `categories`, `options`, `checkbox_icon_type`, `search_options`, `group_id`) VALUES(0, 20, 'Website', 'website', '', '', '', 'website', 'alsp-fa-globe', 0, 1, 0, 0, 0, 'hide', 'hide', 1, 0, 0, 0, 1, 0, 0, 0, 'a:1:{i:0;s:0:\"\";}', 'a:5:{s:8:\"is_blank\";i:1;s:11:\"is_nofollow\";i:1;s:13:\"use_link_text\";i:1;s:17:\"default_link_text\";s:13:\"view our site\";s:21:\"use_default_link_text\";i:0;}', '', '', 1);");
$wpdb->query("INSERT INTO {$wpdb->alsp_content_fields} (`is_core_field`, `order_num`, `name`, `slug`, `description`, `fieldwidth`, `fieldwidth_archive`, `type`, `icon_image`, `is_required`, `is_configuration_page`, `is_search_configuration_page`, `is_ordered`, `is_hide_name`, `is_hide_name_on_grid`, `is_hide_name_on_list`, `is_hide_name_on_search`, `is_field_in_line`, `on_exerpt_page`, `on_exerpt_page_list`, `on_listing_page`, `on_search_form`, `on_map`, `advanced_search_form`, `categories`, `options`, `checkbox_icon_type`, `search_options`, `group_id`) VALUES(0, 21, 'Email', 'email', '', NULL, '', 'email', 'alsp-fa-envelope-o', 0, 0, 0, 0, 0, 'hide', 'hide', 1, 0, 0, 0, 1, 0, 0, 0, '', '', '', '', 1);");
$wpdb->query("INSERT INTO {$wpdb->alsp_content_fields} (`is_core_field`, `order_num`, `name`, `slug`, `description`, `fieldwidth`, `fieldwidth_archive`, `type`, `icon_image`, `is_required`, `is_configuration_page`, `is_search_configuration_page`, `is_ordered`, `is_hide_name`, `is_hide_name_on_grid`, `is_hide_name_on_list`, `is_hide_name_on_search`, `is_field_in_line`, `on_exerpt_page`, `on_exerpt_page_list`, `on_listing_page`, `on_search_form`, `on_map`, `advanced_search_form`, `categories`, `options`, `checkbox_icon_type`, `search_options`, `group_id`) VALUES(0, 1, 'Price', 'price', '', '25', '', 'price', '', 0, 1, 1, 1, 0, 'hide', 'hide', 1, 0, 1, 1, 0, 0, 1, 0, 'a:1:{i:0;s:0:\"\";}', 'a:6:{s:15:\"currency_symbol\";s:1:\"$\";s:17:\"decimal_separator\";s:1:\".\";s:19:\"thousands_separator\";s:0:\"\";s:15:\"symbol_position\";s:1:\"1\";s:13:\"hide_decimals\";s:1:\"1\";s:13:\"range_options\";a:1:{i:0;s:0:\"\";}}', '', 'a:4:{s:4:\"mode\";s:12:\"range_slider\";s:15:\"min_max_options\";N;s:17:\"slider_step_1_min\";s:2:\"25\";s:17:\"slider_step_1_max\";s:2:\"75\";}', 1);");
$wpdb->query("INSERT INTO {$wpdb->alsp_content_fields} (`is_core_field`, `order_num`, `name`, `slug`, `description`, `fieldwidth`, `fieldwidth_archive`, `type`, `icon_image`, `is_required`, `is_configuration_page`, `is_search_configuration_page`, `is_ordered`, `is_hide_name`, `is_hide_name_on_grid`, `is_hide_name_on_list`, `is_hide_name_on_search`, `is_field_in_line`, `on_exerpt_page`, `on_exerpt_page_list`, `on_listing_page`, `on_search_form`, `on_map`, `advanced_search_form`, `categories`, `options`, `checkbox_icon_type`, `search_options`, `group_id`) VALUES(0, 15, 'Method of Payment', 'method_of_payment', '', '75', '', 'checkbox', '', 0, 1, 1, 0, 0, 'hide', 'hide', 1, 0, 0, 0, 1, 0, 0, 0, 'a:1:{i:0;s:0:\"\";}', 'a:4:{s:15:\"selection_items\";a:8:{i:1;s:16:\"American Express\";i:2;s:4:\"Cash\";i:3;s:6:\"Cheque\";i:4;s:8:\"Discover\";i:5;s:8:\"Interact\";i:6;s:10:\"MasterCard\";i:7;s:4:\"Visa\";i:8;s:16:\"Gift Sertificate\";}s:17:\"how_display_items\";s:3:\"all\";s:15:\"check_icon_type\";s:7:\"default\";s:20:\"icon_selection_items\";N;}', '', 'a:1:{s:17:\"search_input_mode\";s:10:\"checkboxes\";}', 0);");
$wpdb->query("INSERT INTO {$wpdb->alsp_content_fields} (`is_core_field`, `order_num`, `name`, `slug`, `description`, `fieldwidth`, `fieldwidth_archive`, `type`, `icon_image`, `is_required`, `is_configuration_page`, `is_search_configuration_page`, `is_ordered`, `is_hide_name`, `is_hide_name_on_grid`, `is_hide_name_on_list`, `is_hide_name_on_search`, `is_field_in_line`, `on_exerpt_page`, `on_exerpt_page_list`, `on_listing_page`, `on_search_form`, `on_map`, `advanced_search_form`, `categories`, `options`, `checkbox_icon_type`, `search_options`, `group_id`) VALUES(0, 11, 'Condition', 'condition', '', '25', '25', 'select', '', 0, 1, 1, 0, 0, 'hide', 'hide', 1, 0, 0, 0, 1, 1, 0, 0, 'a:1:{i:0;s:0:\"\";}', 'a:1:{s:15:\"selection_items\";a:2:{i:1;s:4:\"Used\";i:2;s:9:\"Brand New\";}}', '', 'a:3:{s:17:\"search_input_mode\";s:9:\"selectbox\";s:19:\"checkboxes_operator\";s:2:\"OR\";s:11:\"items_count\";i:1;}', 0);");
$wpdb->query("INSERT INTO {$wpdb->alsp_content_fields} (`is_core_field`, `order_num`, `name`, `slug`, `description`, `fieldwidth`, `fieldwidth_archive`, `type`, `icon_image`, `is_required`, `is_configuration_page`, `is_search_configuration_page`, `is_ordered`, `is_hide_name`, `is_hide_name_on_grid`, `is_hide_name_on_list`, `is_hide_name_on_search`, `is_field_in_line`, `on_exerpt_page`, `on_exerpt_page_list`, `on_listing_page`, `on_search_form`, `on_map`, `advanced_search_form`, `categories`, `options`, `checkbox_icon_type`, `search_options`, `group_id`) VALUES(0, 9, 'Color', 'color', '', '', '', 'string', '', 0, 1, 1, 0, 0, 'hide', 'hide', 1, 0, 0, 0, 1, 0, 0, 0, 'a:0:{}', '', '', '', 0);");
$wpdb->query("INSERT INTO {$wpdb->alsp_content_fields} (`is_core_field`, `order_num`, `name`, `slug`, `description`, `fieldwidth`, `fieldwidth_archive`, `type`, `icon_image`, `is_required`, `is_configuration_page`, `is_search_configuration_page`, `is_ordered`, `is_hide_name`, `is_hide_name_on_grid`, `is_hide_name_on_list`, `is_hide_name_on_search`, `is_field_in_line`, `on_exerpt_page`, `on_exerpt_page_list`, `on_listing_page`, `on_search_form`, `on_map`, `advanced_search_form`, `categories`, `options`, `checkbox_icon_type`, `search_options`, `group_id`) VALUES(0, 10, 'Model Year', 'model_year', '', '25', '25', 'select', '', 0, 1, 1, 0, 0, 'hide', 'hide', 1, 0, 0, 0, 1, 1, 0, 0, 'a:1:{i:0;s:0:\"\";}', 'a:1:{s:15:\"selection_items\";a:80:{i:80;s:4:\"2019\";i:79;s:4:\"2018\";i:1;s:4:\"2017\";i:2;s:4:\"2016\";i:3;s:4:\"2015\";i:4;s:4:\"2014\";i:5;s:4:\"2013\";i:6;s:4:\"2012\";i:7;s:4:\"2011\";i:8;s:4:\"2010\";i:9;s:4:\"2009\";i:10;s:4:\"2008\";i:11;s:4:\"2007\";i:12;s:4:\"2006\";i:13;s:4:\"2005\";i:14;s:4:\"2004\";i:15;s:4:\"2003\";i:16;s:4:\"2002\";i:17;s:4:\"2001\";i:18;s:4:\"2000\";i:19;s:4:\"1999\";i:20;s:4:\"1998\";i:21;s:4:\"1997\";i:22;s:4:\"1996\";i:23;s:4:\"1995\";i:24;s:4:\"1994\";i:25;s:4:\"1993\";i:26;s:4:\"1992\";i:27;s:4:\"1991\";i:28;s:4:\"1990\";i:29;s:4:\"1989\";i:30;s:4:\"1988\";i:31;s:4:\"1987\";i:32;s:4:\"1986\";i:33;s:4:\"1985\";i:34;s:4:\"1984\";i:35;s:4:\"1983\";i:36;s:4:\"1982\";i:37;s:4:\"1981\";i:38;s:4:\"1980\";i:39;s:4:\"1979\";i:40;s:4:\"1978\";i:41;s:4:\"1977\";i:42;s:4:\"1976\";i:43;s:4:\"1975\";i:44;s:4:\"1974\";i:45;s:4:\"1973\";i:46;s:4:\"1972\";i:47;s:4:\"1971\";i:48;s:4:\"1970\";i:49;s:4:\"1969\";i:50;s:4:\"1968\";i:51;s:4:\"1967\";i:52;s:4:\"1966\";i:53;s:4:\"1965\";i:54;s:4:\"1964\";i:55;s:4:\"1963\";i:56;s:4:\"1962\";i:57;s:4:\"1961\";i:58;s:4:\"1960\";i:59;s:4:\"1959\";i:60;s:4:\"1958\";i:61;s:4:\"1957\";i:62;s:4:\"1956\";i:63;s:4:\"1955\";i:64;s:4:\"1954\";i:65;s:4:\"1953\";i:66;s:4:\"1952\";i:67;s:4:\"1951\";i:68;s:4:\"1950\";i:69;s:4:\"1949\";i:70;s:4:\"1948\";i:71;s:4:\"1947\";i:72;s:4:\"1946\";i:73;s:4:\"1945\";i:74;s:4:\"1944\";i:75;s:4:\"1943\";i:76;s:4:\"1942\";i:77;s:4:\"1941\";i:78;s:4:\"1940\";}}', '', 'a:3:{s:17:\"search_input_mode\";s:9:\"selectbox\";s:19:\"checkboxes_operator\";s:2:\"OR\";s:11:\"items_count\";i:1;}', 0);");
$wpdb->query("INSERT INTO {$wpdb->alsp_content_fields} (`is_core_field`, `order_num`, `name`, `slug`, `description`, `fieldwidth`, `fieldwidth_archive`, `type`, `icon_image`, `is_required`, `is_configuration_page`, `is_search_configuration_page`, `is_ordered`, `is_hide_name`, `is_hide_name_on_grid`, `is_hide_name_on_list`, `is_hide_name_on_search`, `is_field_in_line`, `on_exerpt_page`, `on_exerpt_page_list`, `on_listing_page`, `on_search_form`, `on_map`, `advanced_search_form`, `categories`, `options`, `checkbox_icon_type`, `search_options`, `group_id`) VALUES(0, 13, 'Seller type', 'seller_type', '', '25', '', 'select', '', 0, 1, 1, 0, 0, 'hide', 'hide', 1, 0, 0, 0, 1, 0, 0, 0, 'a:1:{i:0;s:0:\"\";}', 'a:1:{s:15:\"selection_items\";a:2:{i:1;s:6:\"Agency\";i:2;s:8:\"Personal\";}}', '', 'a:3:{s:17:\"search_input_mode\";s:9:\"selectbox\";s:19:\"checkboxes_operator\";s:2:\"OR\";s:11:\"items_count\";i:1;}', 0);");
$wpdb->query("INSERT INTO {$wpdb->alsp_content_fields} (`is_core_field`, `order_num`, `name`, `slug`, `description`, `fieldwidth`, `fieldwidth_archive`, `type`, `icon_image`, `is_required`, `is_configuration_page`, `is_search_configuration_page`, `is_ordered`, `is_hide_name`, `is_hide_name_on_grid`, `is_hide_name_on_list`, `is_hide_name_on_search`, `is_field_in_line`, `on_exerpt_page`, `on_exerpt_page_list`, `on_listing_page`, `on_search_form`, `on_map`, `advanced_search_form`, `categories`, `options`, `checkbox_icon_type`, `search_options`, `group_id`) VALUES(0, 12, 'Registered City', 'registered-city', '', '', '', 'string', '', 0, 1, 1, 0, 0, 'hide', 'hide', 1, 0, 0, 0, 1, 0, 0, 0, 'a:0:{}', '', '', '', 0);");
$wpdb->query("INSERT INTO {$wpdb->alsp_content_fields} (`is_core_field`, `order_num`, `name`, `slug`, `description`, `fieldwidth`, `fieldwidth_archive`, `type`, `icon_image`, `is_required`, `is_configuration_page`, `is_search_configuration_page`, `is_ordered`, `is_hide_name`, `is_hide_name_on_grid`, `is_hide_name_on_list`, `is_hide_name_on_search`, `is_field_in_line`, `on_exerpt_page`, `on_exerpt_page_list`, `on_listing_page`, `on_search_form`, `on_map`, `advanced_search_form`, `categories`, `options`, `checkbox_icon_type`, `search_options`, `group_id`) VALUES(0, 8, 'Engine Capacity', 'engine-capacity', '', '', '', 'string', '', 0, 1, 1, 0, 0, 'hide', 'hide', 1, 0, 1, 0, 1, 1, 0, 0, 'a:1:{i:0;s:0:\"\";}', '', '', '', 0);");
$wpdb->query("INSERT INTO {$wpdb->alsp_content_fields} (`is_core_field`, `order_num`, `name`, `slug`, `description`, `fieldwidth`, `fieldwidth_archive`, `type`, `icon_image`, `is_required`, `is_configuration_page`, `is_search_configuration_page`, `is_ordered`, `is_hide_name`, `is_hide_name_on_grid`, `is_hide_name_on_list`, `is_hide_name_on_search`, `is_field_in_line`, `on_exerpt_page`, `on_exerpt_page_list`, `on_listing_page`, `on_search_form`, `on_map`, `advanced_search_form`, `categories`, `options`, `checkbox_icon_type`, `search_options`, `group_id`) VALUES(0, 14, 'Car Features', 'car-features', '', '', '', 'checkbox', '', 0, 1, 1, 0, 0, 'hide', 'hide', 1, 0, 0, 0, 1, 0, 0, 0, 'a:0:{}', 'a:4:{s:15:\"selection_items\";a:16:{i:1;s:3:\"ABS\";i:2;s:11:\"AM/FM Radio\";i:3;s:8:\"Air Bags\";i:4;s:16:\"Air Conditioning\";i:5;s:10:\"Alloy Rims\";i:6;s:9:\"CD Player\";i:7;s:15:\"Immobilizer Key\";i:8;s:13:\"Keyless Entry\";i:9;s:11:\"Power Locks\";i:10;s:13:\"Power Mirrors\";i:11;s:14:\"Power Steering\";i:12;s:13:\"Power Windows\";i:13;s:13:\"Rear AC Vents\";i:14;s:13:\"Rear speakers\";i:15;s:8:\"Sun Roof\";i:16;s:23:\"USB and Auxillary Cable\";}s:17:\"how_display_items\";s:3:\"all\";s:15:\"check_icon_type\";s:7:\"default\";s:20:\"icon_selection_items\";N;}', '', '', 0);");
$wpdb->query("INSERT INTO {$wpdb->alsp_content_fields} (`is_core_field`, `order_num`, `name`, `slug`, `description`, `fieldwidth`, `fieldwidth_archive`, `type`, `icon_image`, `is_required`, `is_configuration_page`, `is_search_configuration_page`, `is_ordered`, `is_hide_name`, `is_hide_name_on_grid`, `is_hide_name_on_list`, `is_hide_name_on_search`, `is_field_in_line`, `on_exerpt_page`, `on_exerpt_page_list`, `on_listing_page`, `on_search_form`, `on_map`, `advanced_search_form`, `categories`, `options`, `checkbox_icon_type`, `search_options`, `group_id`) VALUES(0, 2, 'Other Model', 'other_model', '', '', '', 'string', '', 0, 1, 1, 0, 0, 'hide', 'hide', 1, 0, 1, 0, 1, 0, 0, 0, 'a:1:{i:0;s:0:\"\";}', '', '', '', 0);");
$wpdb->query("INSERT INTO {$wpdb->alsp_content_fields} (`is_core_field`, `order_num`, `name`, `slug`, `description`, `fieldwidth`, `fieldwidth_archive`, `type`, `icon_image`, `is_required`, `is_configuration_page`, `is_search_configuration_page`, `is_ordered`, `is_hide_name`, `is_hide_name_on_grid`, `is_hide_name_on_list`, `is_hide_name_on_search`, `is_field_in_line`, `on_exerpt_page`, `on_exerpt_page_list`, `on_listing_page`, `on_search_form`, `on_map`, `advanced_search_form`, `categories`, `options`, `checkbox_icon_type`, `search_options`, `group_id`) VALUES(0, 4, 'Litres', 'liters', '', '', '', 'string', '', 0, 1, 1, 0, 0, 'hide', 'hide', 1, 0, 1, 0, 1, 0, 0, 0, 'a:1:{i:0;s:0:\"\";}', '', '', '', 0);");
$wpdb->query("INSERT INTO {$wpdb->alsp_content_fields} (`is_core_field`, `order_num`, `name`, `slug`, `description`, `fieldwidth`, `fieldwidth_archive`, `type`, `icon_image`, `is_required`, `is_configuration_page`, `is_search_configuration_page`, `is_ordered`, `is_hide_name`, `is_hide_name_on_grid`, `is_hide_name_on_list`, `is_hide_name_on_search`, `is_field_in_line`, `on_exerpt_page`, `on_exerpt_page_list`, `on_listing_page`, `on_search_form`, `on_map`, `advanced_search_form`, `categories`, `options`, `checkbox_icon_type`, `search_options`, `group_id`) VALUES(0, 3, 'Mileage', 'mileage', '', '', '', 'number', 'pacz-automotive-street', 0, 1, 1, 0, 0, 'show_only_icon', 'show_only_icon', 1, 1, 1, 1, 1, 0, 0, 0, 'a:1:{i:0;s:0:\"\";}', 'a:5:{s:10:\"is_integer\";s:1:\"1\";s:17:\"decimal_separator\";s:1:\",\";s:19:\"thousands_separator\";s:0:\"\";s:3:\"min\";s:1:\"0\";s:3:\"max\";s:0:\"\";}', '', '', 0);");
$wpdb->query("INSERT INTO {$wpdb->alsp_content_fields} (`is_core_field`, `order_num`, `name`, `slug`, `description`, `fieldwidth`, `fieldwidth_archive`, `type`, `icon_image`, `is_required`, `is_configuration_page`, `is_search_configuration_page`, `is_ordered`, `is_hide_name`, `is_hide_name_on_grid`, `is_hide_name_on_list`, `is_hide_name_on_search`, `is_field_in_line`, `on_exerpt_page`, `on_exerpt_page_list`, `on_listing_page`, `on_search_form`, `on_map`, `advanced_search_form`, `categories`, `options`, `checkbox_icon_type`, `search_options`, `group_id`) VALUES(0, 5, 'Convertible', 'convertible', '', '25', '25', 'select', '', 0, 1, 1, 0, 0, 'hide', 'hide', 1, 0, 0, 0, 1, 0, 0, 0, 'a:1:{i:0;s:0:\"\";}', 'a:1:{s:15:\"selection_items\";a:2:{i:1;s:3:\"Yes\";i:2;s:2:\"No\";}}', '', 'a:3:{s:17:\"search_input_mode\";s:9:\"selectbox\";s:19:\"checkboxes_operator\";s:2:\"OR\";s:11:\"items_count\";i:1;}', 0);");
$wpdb->query("INSERT INTO {$wpdb->alsp_content_fields} (`is_core_field`, `order_num`, `name`, `slug`, `description`, `fieldwidth`, `fieldwidth_archive`, `type`, `icon_image`, `is_required`, `is_configuration_page`, `is_search_configuration_page`, `is_ordered`, `is_hide_name`, `is_hide_name_on_grid`, `is_hide_name_on_list`, `is_hide_name_on_search`, `is_field_in_line`, `on_exerpt_page`, `on_exerpt_page_list`, `on_listing_page`, `on_search_form`, `on_map`, `advanced_search_form`, `categories`, `options`, `checkbox_icon_type`, `search_options`, `group_id`) VALUES(0, 6, 'Transmission', 'transmission', '', '25', '25', 'select', 'pacz-automotive-gearshift', 0, 1, 1, 0, 0, 'show_only_icon', 'show_only_icon', 1, 1, 1, 1, 1, 1, 0, 0, 'a:1:{i:0;s:0:\"\";}', 'a:1:{s:15:\"selection_items\";a:3:{i:1;s:6:\"Manual\";i:2;s:14:\"Semi Automatic\";i:3;s:9:\"Automatic\";}}', '', 'a:3:{s:17:\"search_input_mode\";s:9:\"selectbox\";s:19:\"checkboxes_operator\";s:2:\"OR\";s:11:\"items_count\";i:1;}', 0);");
$wpdb->query("INSERT INTO {$wpdb->alsp_content_fields} (`is_core_field`, `order_num`, `name`, `slug`, `description`, `fieldwidth`, `fieldwidth_archive`, `type`, `icon_image`, `is_required`, `is_configuration_page`, `is_search_configuration_page`, `is_ordered`, `is_hide_name`, `is_hide_name_on_grid`, `is_hide_name_on_list`, `is_hide_name_on_search`, `is_field_in_line`, `on_exerpt_page`, `on_exerpt_page_list`, `on_listing_page`, `on_search_form`, `on_map`, `advanced_search_form`, `categories`, `options`, `checkbox_icon_type`, `search_options`, `group_id`) VALUES(0, 7, 'Seats', 'seats', '', '', '', 'select', 'pacz-automotive-seat', 0, 1, 1, 0, 0, 'show_only_icon', 'show_only_icon', 1, 1, 1, 1, 1, 0, 0, 0, 'a:1:{i:0;s:0:\"\";}', 'a:1:{s:15:\"selection_items\";a:4:{i:1;s:1:\"2\";i:2;s:1:\"4\";i:3;s:1:\"5\";i:4;s:1:\"7\";}}', '', '', 0);");

}
